mvn install:install-file -Dfile=lib/gluegen-rt-natives-linux-amd64.jar -DgroupId=self -DartifactId=gluegen-rt-natives-linux-amd64 -Dversion=912.1822 -Dpackaging=jar
mvn install:install-file -Dfile=lib/gluegen-rt-natives-linux-i586.jar -DgroupId=self -DartifactId=gluegen-rt-natives-linux-i586 -Dversion=912.1822 -Dpackaging=jar
mvn install:install-file -Dfile=lib/gluegen-rt-natives-macosx-universal.jar -DgroupId=self -DartifactId=gluegen-rt-natives-macosx-universal -Dversion=912.1822 -Dpackaging=jar
mvn install:install-file -Dfile=lib/jogl-all-natives-linux-amd64.jar -DgroupId=self -DartifactId=jogl-all-natives-linux-amd64 -Dversion=912.1822 -Dpackaging=jar
mvn install:install-file -Dfile=lib/jogl-all-natives-linux-i586.jar -DgroupId=self -DartifactId=jogl-all-natives-linux-i586 -Dversion=912.1822 -Dpackaging=jar
mvn install:install-file -Dfile=lib/jogl-all-natives-macosx-universal.jar -DgroupId=self -DartifactId=jogl-all-natives-macosx-universal -Dversion=912.1822 -Dpackaging=jar
mvn install:install-file -Dfile=lib/gluegen-rt-natives-windows-amd64.jar -DgroupId=self -DartifactId=gluegen-rt-natives-windows-amd64 -Dversion=912.1822 -Dpackaging=jar
mvn install:install-file -Dfile=lib/gluegen-rt-natives-windows-i586.jar -DgroupId=self -DartifactId=gluegen-rt-natives-windows-i586 -Dversion=912.1822 -Dpackaging=jar
mvn install:install-file -Dfile=lib/jogl-all-natives-windows-amd64.jar -DgroupId=self -DartifactId=jogl-all-natives-windows-amd64 -Dversion=912.1822 -Dpackaging=jar
mvn install:install-file -Dfile=lib/jogl-all-natives-windows-i586.jar -DgroupId=self -DartifactId=jogl-all-natives-windows-i586 -Dversion=912.1822 -Dpackaging=jar