// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: LakeContainer.proto

package com.chunkmapper.protoc;

public final class LakeContainer {
  private LakeContainer() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }
  public interface LakeOrBuilder
      extends com.google.protobuf.MessageLiteOrBuilder {

    // repeated .Point points = 1;
    /**
     * <code>repeated .Point points = 1;</code>
     */
    java.util.List<com.chunkmapper.protoc.PointContainer.Point> 
        getPointsList();
    /**
     * <code>repeated .Point points = 1;</code>
     */
    com.chunkmapper.protoc.PointContainer.Point getPoints(int index);
    /**
     * <code>repeated .Point points = 1;</code>
     */
    int getPointsCount();

    // required .Rectangle bbox = 2;
    /**
     * <code>required .Rectangle bbox = 2;</code>
     */
    boolean hasBbox();
    /**
     * <code>required .Rectangle bbox = 2;</code>
     */
    com.chunkmapper.protoc.RectangleContainer.Rectangle getBbox();

    // optional bool is_inner = 3;
    /**
     * <code>optional bool is_inner = 3;</code>
     */
    boolean hasIsInner();
    /**
     * <code>optional bool is_inner = 3;</code>
     */
    boolean getIsInner();
  }
  /**
   * Protobuf type {@code Lake}
   */
  public static final class Lake extends
      com.google.protobuf.GeneratedMessageLite
      implements LakeOrBuilder {
    // Use Lake.newBuilder() to construct.
    private Lake(com.google.protobuf.GeneratedMessageLite.Builder builder) {
      super(builder);

    }
    private Lake(boolean noInit) {}

    private static final Lake defaultInstance;
    public static Lake getDefaultInstance() {
      return defaultInstance;
    }

    public Lake getDefaultInstanceForType() {
      return defaultInstance;
    }

    private Lake(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 10: {
              if (!((mutable_bitField0_ & 0x00000001) == 0x00000001)) {
                points_ = new java.util.ArrayList<com.chunkmapper.protoc.PointContainer.Point>();
                mutable_bitField0_ |= 0x00000001;
              }
              points_.add(input.readMessage(com.chunkmapper.protoc.PointContainer.Point.PARSER, extensionRegistry));
              break;
            }
            case 18: {
              com.chunkmapper.protoc.RectangleContainer.Rectangle.Builder subBuilder = null;
              if (((bitField0_ & 0x00000001) == 0x00000001)) {
                subBuilder = bbox_.toBuilder();
              }
              bbox_ = input.readMessage(com.chunkmapper.protoc.RectangleContainer.Rectangle.PARSER, extensionRegistry);
              if (subBuilder != null) {
                subBuilder.mergeFrom(bbox_);
                bbox_ = subBuilder.buildPartial();
              }
              bitField0_ |= 0x00000001;
              break;
            }
            case 24: {
              bitField0_ |= 0x00000002;
              isInner_ = input.readBool();
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        if (((mutable_bitField0_ & 0x00000001) == 0x00000001)) {
          points_ = java.util.Collections.unmodifiableList(points_);
        }
        makeExtensionsImmutable();
      }
    }
    public static com.google.protobuf.Parser<Lake> PARSER =
        new com.google.protobuf.AbstractParser<Lake>() {
      public Lake parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new Lake(input, extensionRegistry);
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<Lake> getParserForType() {
      return PARSER;
    }

    private int bitField0_;
    // repeated .Point points = 1;
    public static final int POINTS_FIELD_NUMBER = 1;
    private java.util.List<com.chunkmapper.protoc.PointContainer.Point> points_;
    /**
     * <code>repeated .Point points = 1;</code>
     */
    public java.util.List<com.chunkmapper.protoc.PointContainer.Point> getPointsList() {
      return points_;
    }
    /**
     * <code>repeated .Point points = 1;</code>
     */
    public java.util.List<? extends com.chunkmapper.protoc.PointContainer.PointOrBuilder> 
        getPointsOrBuilderList() {
      return points_;
    }
    /**
     * <code>repeated .Point points = 1;</code>
     */
    public int getPointsCount() {
      return points_.size();
    }
    /**
     * <code>repeated .Point points = 1;</code>
     */
    public com.chunkmapper.protoc.PointContainer.Point getPoints(int index) {
      return points_.get(index);
    }
    /**
     * <code>repeated .Point points = 1;</code>
     */
    public com.chunkmapper.protoc.PointContainer.PointOrBuilder getPointsOrBuilder(
        int index) {
      return points_.get(index);
    }

    // required .Rectangle bbox = 2;
    public static final int BBOX_FIELD_NUMBER = 2;
    private com.chunkmapper.protoc.RectangleContainer.Rectangle bbox_;
    /**
     * <code>required .Rectangle bbox = 2;</code>
     */
    public boolean hasBbox() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>required .Rectangle bbox = 2;</code>
     */
    public com.chunkmapper.protoc.RectangleContainer.Rectangle getBbox() {
      return bbox_;
    }

    // optional bool is_inner = 3;
    public static final int IS_INNER_FIELD_NUMBER = 3;
    private boolean isInner_;
    /**
     * <code>optional bool is_inner = 3;</code>
     */
    public boolean hasIsInner() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    /**
     * <code>optional bool is_inner = 3;</code>
     */
    public boolean getIsInner() {
      return isInner_;
    }

    private void initFields() {
      points_ = java.util.Collections.emptyList();
      bbox_ = com.chunkmapper.protoc.RectangleContainer.Rectangle.getDefaultInstance();
      isInner_ = false;
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;

      if (!hasBbox()) {
        memoizedIsInitialized = 0;
        return false;
      }
      for (int i = 0; i < getPointsCount(); i++) {
        if (!getPoints(i).isInitialized()) {
          memoizedIsInitialized = 0;
          return false;
        }
      }
      if (!getBbox().isInitialized()) {
        memoizedIsInitialized = 0;
        return false;
      }
      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      for (int i = 0; i < points_.size(); i++) {
        output.writeMessage(1, points_.get(i));
      }
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeMessage(2, bbox_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeBool(3, isInner_);
      }
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      for (int i = 0; i < points_.size(); i++) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(1, points_.get(i));
      }
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(2, bbox_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBoolSize(3, isInner_);
      }
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static com.chunkmapper.protoc.LakeContainer.Lake parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.chunkmapper.protoc.LakeContainer.Lake parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.chunkmapper.protoc.LakeContainer.Lake parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.chunkmapper.protoc.LakeContainer.Lake parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.chunkmapper.protoc.LakeContainer.Lake parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.chunkmapper.protoc.LakeContainer.Lake parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static com.chunkmapper.protoc.LakeContainer.Lake parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static com.chunkmapper.protoc.LakeContainer.Lake parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static com.chunkmapper.protoc.LakeContainer.Lake parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.chunkmapper.protoc.LakeContainer.Lake parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(com.chunkmapper.protoc.LakeContainer.Lake prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    /**
     * Protobuf type {@code Lake}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageLite.Builder<
          com.chunkmapper.protoc.LakeContainer.Lake, Builder>
        implements com.chunkmapper.protoc.LakeContainer.LakeOrBuilder {
      // Construct using com.chunkmapper.protoc.LakeContainer.Lake.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private void maybeForceBuilderInitialization() {
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        points_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000001);
        bbox_ = com.chunkmapper.protoc.RectangleContainer.Rectangle.getDefaultInstance();
        bitField0_ = (bitField0_ & ~0x00000002);
        isInner_ = false;
        bitField0_ = (bitField0_ & ~0x00000004);
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.chunkmapper.protoc.LakeContainer.Lake getDefaultInstanceForType() {
        return com.chunkmapper.protoc.LakeContainer.Lake.getDefaultInstance();
      }

      public com.chunkmapper.protoc.LakeContainer.Lake build() {
        com.chunkmapper.protoc.LakeContainer.Lake result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public com.chunkmapper.protoc.LakeContainer.Lake buildPartial() {
        com.chunkmapper.protoc.LakeContainer.Lake result = new com.chunkmapper.protoc.LakeContainer.Lake(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((bitField0_ & 0x00000001) == 0x00000001)) {
          points_ = java.util.Collections.unmodifiableList(points_);
          bitField0_ = (bitField0_ & ~0x00000001);
        }
        result.points_ = points_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000001;
        }
        result.bbox_ = bbox_;
        if (((from_bitField0_ & 0x00000004) == 0x00000004)) {
          to_bitField0_ |= 0x00000002;
        }
        result.isInner_ = isInner_;
        result.bitField0_ = to_bitField0_;
        return result;
      }

      public Builder mergeFrom(com.chunkmapper.protoc.LakeContainer.Lake other) {
        if (other == com.chunkmapper.protoc.LakeContainer.Lake.getDefaultInstance()) return this;
        if (!other.points_.isEmpty()) {
          if (points_.isEmpty()) {
            points_ = other.points_;
            bitField0_ = (bitField0_ & ~0x00000001);
          } else {
            ensurePointsIsMutable();
            points_.addAll(other.points_);
          }
          
        }
        if (other.hasBbox()) {
          mergeBbox(other.getBbox());
        }
        if (other.hasIsInner()) {
          setIsInner(other.getIsInner());
        }
        return this;
      }

      public final boolean isInitialized() {
        if (!hasBbox()) {
          
          return false;
        }
        for (int i = 0; i < getPointsCount(); i++) {
          if (!getPoints(i).isInitialized()) {
            
            return false;
          }
        }
        if (!getBbox().isInitialized()) {
          
          return false;
        }
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.chunkmapper.protoc.LakeContainer.Lake parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.chunkmapper.protoc.LakeContainer.Lake) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      // repeated .Point points = 1;
      private java.util.List<com.chunkmapper.protoc.PointContainer.Point> points_ =
        java.util.Collections.emptyList();
      private void ensurePointsIsMutable() {
        if (!((bitField0_ & 0x00000001) == 0x00000001)) {
          points_ = new java.util.ArrayList<com.chunkmapper.protoc.PointContainer.Point>(points_);
          bitField0_ |= 0x00000001;
         }
      }

      /**
       * <code>repeated .Point points = 1;</code>
       */
      public java.util.List<com.chunkmapper.protoc.PointContainer.Point> getPointsList() {
        return java.util.Collections.unmodifiableList(points_);
      }
      /**
       * <code>repeated .Point points = 1;</code>
       */
      public int getPointsCount() {
        return points_.size();
      }
      /**
       * <code>repeated .Point points = 1;</code>
       */
      public com.chunkmapper.protoc.PointContainer.Point getPoints(int index) {
        return points_.get(index);
      }
      /**
       * <code>repeated .Point points = 1;</code>
       */
      public Builder setPoints(
          int index, com.chunkmapper.protoc.PointContainer.Point value) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensurePointsIsMutable();
        points_.set(index, value);

        return this;
      }
      /**
       * <code>repeated .Point points = 1;</code>
       */
      public Builder setPoints(
          int index, com.chunkmapper.protoc.PointContainer.Point.Builder builderForValue) {
        ensurePointsIsMutable();
        points_.set(index, builderForValue.build());

        return this;
      }
      /**
       * <code>repeated .Point points = 1;</code>
       */
      public Builder addPoints(com.chunkmapper.protoc.PointContainer.Point value) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensurePointsIsMutable();
        points_.add(value);

        return this;
      }
      /**
       * <code>repeated .Point points = 1;</code>
       */
      public Builder addPoints(
          int index, com.chunkmapper.protoc.PointContainer.Point value) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensurePointsIsMutable();
        points_.add(index, value);

        return this;
      }
      /**
       * <code>repeated .Point points = 1;</code>
       */
      public Builder addPoints(
          com.chunkmapper.protoc.PointContainer.Point.Builder builderForValue) {
        ensurePointsIsMutable();
        points_.add(builderForValue.build());

        return this;
      }
      /**
       * <code>repeated .Point points = 1;</code>
       */
      public Builder addPoints(
          int index, com.chunkmapper.protoc.PointContainer.Point.Builder builderForValue) {
        ensurePointsIsMutable();
        points_.add(index, builderForValue.build());

        return this;
      }
      /**
       * <code>repeated .Point points = 1;</code>
       */
      public Builder addAllPoints(
          java.lang.Iterable<? extends com.chunkmapper.protoc.PointContainer.Point> values) {
        ensurePointsIsMutable();
        super.addAll(values, points_);

        return this;
      }
      /**
       * <code>repeated .Point points = 1;</code>
       */
      public Builder clearPoints() {
        points_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000001);

        return this;
      }
      /**
       * <code>repeated .Point points = 1;</code>
       */
      public Builder removePoints(int index) {
        ensurePointsIsMutable();
        points_.remove(index);

        return this;
      }

      // required .Rectangle bbox = 2;
      private com.chunkmapper.protoc.RectangleContainer.Rectangle bbox_ = com.chunkmapper.protoc.RectangleContainer.Rectangle.getDefaultInstance();
      /**
       * <code>required .Rectangle bbox = 2;</code>
       */
      public boolean hasBbox() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      /**
       * <code>required .Rectangle bbox = 2;</code>
       */
      public com.chunkmapper.protoc.RectangleContainer.Rectangle getBbox() {
        return bbox_;
      }
      /**
       * <code>required .Rectangle bbox = 2;</code>
       */
      public Builder setBbox(com.chunkmapper.protoc.RectangleContainer.Rectangle value) {
        if (value == null) {
          throw new NullPointerException();
        }
        bbox_ = value;

        bitField0_ |= 0x00000002;
        return this;
      }
      /**
       * <code>required .Rectangle bbox = 2;</code>
       */
      public Builder setBbox(
          com.chunkmapper.protoc.RectangleContainer.Rectangle.Builder builderForValue) {
        bbox_ = builderForValue.build();

        bitField0_ |= 0x00000002;
        return this;
      }
      /**
       * <code>required .Rectangle bbox = 2;</code>
       */
      public Builder mergeBbox(com.chunkmapper.protoc.RectangleContainer.Rectangle value) {
        if (((bitField0_ & 0x00000002) == 0x00000002) &&
            bbox_ != com.chunkmapper.protoc.RectangleContainer.Rectangle.getDefaultInstance()) {
          bbox_ =
            com.chunkmapper.protoc.RectangleContainer.Rectangle.newBuilder(bbox_).mergeFrom(value).buildPartial();
        } else {
          bbox_ = value;
        }

        bitField0_ |= 0x00000002;
        return this;
      }
      /**
       * <code>required .Rectangle bbox = 2;</code>
       */
      public Builder clearBbox() {
        bbox_ = com.chunkmapper.protoc.RectangleContainer.Rectangle.getDefaultInstance();

        bitField0_ = (bitField0_ & ~0x00000002);
        return this;
      }

      // optional bool is_inner = 3;
      private boolean isInner_ ;
      /**
       * <code>optional bool is_inner = 3;</code>
       */
      public boolean hasIsInner() {
        return ((bitField0_ & 0x00000004) == 0x00000004);
      }
      /**
       * <code>optional bool is_inner = 3;</code>
       */
      public boolean getIsInner() {
        return isInner_;
      }
      /**
       * <code>optional bool is_inner = 3;</code>
       */
      public Builder setIsInner(boolean value) {
        bitField0_ |= 0x00000004;
        isInner_ = value;
        
        return this;
      }
      /**
       * <code>optional bool is_inner = 3;</code>
       */
      public Builder clearIsInner() {
        bitField0_ = (bitField0_ & ~0x00000004);
        isInner_ = false;
        
        return this;
      }

      // @@protoc_insertion_point(builder_scope:Lake)
    }

    static {
      defaultInstance = new Lake(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:Lake)
  }

  public interface LakeRegionOrBuilder
      extends com.google.protobuf.MessageLiteOrBuilder {

    // repeated .Lake lakes = 1;
    /**
     * <code>repeated .Lake lakes = 1;</code>
     */
    java.util.List<com.chunkmapper.protoc.LakeContainer.Lake> 
        getLakesList();
    /**
     * <code>repeated .Lake lakes = 1;</code>
     */
    com.chunkmapper.protoc.LakeContainer.Lake getLakes(int index);
    /**
     * <code>repeated .Lake lakes = 1;</code>
     */
    int getLakesCount();
  }
  /**
   * Protobuf type {@code LakeRegion}
   */
  public static final class LakeRegion extends
      com.google.protobuf.GeneratedMessageLite
      implements LakeRegionOrBuilder {
    // Use LakeRegion.newBuilder() to construct.
    private LakeRegion(com.google.protobuf.GeneratedMessageLite.Builder builder) {
      super(builder);

    }
    private LakeRegion(boolean noInit) {}

    private static final LakeRegion defaultInstance;
    public static LakeRegion getDefaultInstance() {
      return defaultInstance;
    }

    public LakeRegion getDefaultInstanceForType() {
      return defaultInstance;
    }

    private LakeRegion(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 10: {
              if (!((mutable_bitField0_ & 0x00000001) == 0x00000001)) {
                lakes_ = new java.util.ArrayList<com.chunkmapper.protoc.LakeContainer.Lake>();
                mutable_bitField0_ |= 0x00000001;
              }
              lakes_.add(input.readMessage(com.chunkmapper.protoc.LakeContainer.Lake.PARSER, extensionRegistry));
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        if (((mutable_bitField0_ & 0x00000001) == 0x00000001)) {
          lakes_ = java.util.Collections.unmodifiableList(lakes_);
        }
        makeExtensionsImmutable();
      }
    }
    public static com.google.protobuf.Parser<LakeRegion> PARSER =
        new com.google.protobuf.AbstractParser<LakeRegion>() {
      public LakeRegion parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new LakeRegion(input, extensionRegistry);
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<LakeRegion> getParserForType() {
      return PARSER;
    }

    // repeated .Lake lakes = 1;
    public static final int LAKES_FIELD_NUMBER = 1;
    private java.util.List<com.chunkmapper.protoc.LakeContainer.Lake> lakes_;
    /**
     * <code>repeated .Lake lakes = 1;</code>
     */
    public java.util.List<com.chunkmapper.protoc.LakeContainer.Lake> getLakesList() {
      return lakes_;
    }
    /**
     * <code>repeated .Lake lakes = 1;</code>
     */
    public java.util.List<? extends com.chunkmapper.protoc.LakeContainer.LakeOrBuilder> 
        getLakesOrBuilderList() {
      return lakes_;
    }
    /**
     * <code>repeated .Lake lakes = 1;</code>
     */
    public int getLakesCount() {
      return lakes_.size();
    }
    /**
     * <code>repeated .Lake lakes = 1;</code>
     */
    public com.chunkmapper.protoc.LakeContainer.Lake getLakes(int index) {
      return lakes_.get(index);
    }
    /**
     * <code>repeated .Lake lakes = 1;</code>
     */
    public com.chunkmapper.protoc.LakeContainer.LakeOrBuilder getLakesOrBuilder(
        int index) {
      return lakes_.get(index);
    }

    private void initFields() {
      lakes_ = java.util.Collections.emptyList();
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;

      for (int i = 0; i < getLakesCount(); i++) {
        if (!getLakes(i).isInitialized()) {
          memoizedIsInitialized = 0;
          return false;
        }
      }
      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      for (int i = 0; i < lakes_.size(); i++) {
        output.writeMessage(1, lakes_.get(i));
      }
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      for (int i = 0; i < lakes_.size(); i++) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(1, lakes_.get(i));
      }
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static com.chunkmapper.protoc.LakeContainer.LakeRegion parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.chunkmapper.protoc.LakeContainer.LakeRegion parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.chunkmapper.protoc.LakeContainer.LakeRegion parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.chunkmapper.protoc.LakeContainer.LakeRegion parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.chunkmapper.protoc.LakeContainer.LakeRegion parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.chunkmapper.protoc.LakeContainer.LakeRegion parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static com.chunkmapper.protoc.LakeContainer.LakeRegion parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static com.chunkmapper.protoc.LakeContainer.LakeRegion parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static com.chunkmapper.protoc.LakeContainer.LakeRegion parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.chunkmapper.protoc.LakeContainer.LakeRegion parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(com.chunkmapper.protoc.LakeContainer.LakeRegion prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    /**
     * Protobuf type {@code LakeRegion}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageLite.Builder<
          com.chunkmapper.protoc.LakeContainer.LakeRegion, Builder>
        implements com.chunkmapper.protoc.LakeContainer.LakeRegionOrBuilder {
      // Construct using com.chunkmapper.protoc.LakeContainer.LakeRegion.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private void maybeForceBuilderInitialization() {
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        lakes_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000001);
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.chunkmapper.protoc.LakeContainer.LakeRegion getDefaultInstanceForType() {
        return com.chunkmapper.protoc.LakeContainer.LakeRegion.getDefaultInstance();
      }

      public com.chunkmapper.protoc.LakeContainer.LakeRegion build() {
        com.chunkmapper.protoc.LakeContainer.LakeRegion result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public com.chunkmapper.protoc.LakeContainer.LakeRegion buildPartial() {
        com.chunkmapper.protoc.LakeContainer.LakeRegion result = new com.chunkmapper.protoc.LakeContainer.LakeRegion(this);
        int from_bitField0_ = bitField0_;
        if (((bitField0_ & 0x00000001) == 0x00000001)) {
          lakes_ = java.util.Collections.unmodifiableList(lakes_);
          bitField0_ = (bitField0_ & ~0x00000001);
        }
        result.lakes_ = lakes_;
        return result;
      }

      public Builder mergeFrom(com.chunkmapper.protoc.LakeContainer.LakeRegion other) {
        if (other == com.chunkmapper.protoc.LakeContainer.LakeRegion.getDefaultInstance()) return this;
        if (!other.lakes_.isEmpty()) {
          if (lakes_.isEmpty()) {
            lakes_ = other.lakes_;
            bitField0_ = (bitField0_ & ~0x00000001);
          } else {
            ensureLakesIsMutable();
            lakes_.addAll(other.lakes_);
          }
          
        }
        return this;
      }

      public final boolean isInitialized() {
        for (int i = 0; i < getLakesCount(); i++) {
          if (!getLakes(i).isInitialized()) {
            
            return false;
          }
        }
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.chunkmapper.protoc.LakeContainer.LakeRegion parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.chunkmapper.protoc.LakeContainer.LakeRegion) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      // repeated .Lake lakes = 1;
      private java.util.List<com.chunkmapper.protoc.LakeContainer.Lake> lakes_ =
        java.util.Collections.emptyList();
      private void ensureLakesIsMutable() {
        if (!((bitField0_ & 0x00000001) == 0x00000001)) {
          lakes_ = new java.util.ArrayList<com.chunkmapper.protoc.LakeContainer.Lake>(lakes_);
          bitField0_ |= 0x00000001;
         }
      }

      /**
       * <code>repeated .Lake lakes = 1;</code>
       */
      public java.util.List<com.chunkmapper.protoc.LakeContainer.Lake> getLakesList() {
        return java.util.Collections.unmodifiableList(lakes_);
      }
      /**
       * <code>repeated .Lake lakes = 1;</code>
       */
      public int getLakesCount() {
        return lakes_.size();
      }
      /**
       * <code>repeated .Lake lakes = 1;</code>
       */
      public com.chunkmapper.protoc.LakeContainer.Lake getLakes(int index) {
        return lakes_.get(index);
      }
      /**
       * <code>repeated .Lake lakes = 1;</code>
       */
      public Builder setLakes(
          int index, com.chunkmapper.protoc.LakeContainer.Lake value) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureLakesIsMutable();
        lakes_.set(index, value);

        return this;
      }
      /**
       * <code>repeated .Lake lakes = 1;</code>
       */
      public Builder setLakes(
          int index, com.chunkmapper.protoc.LakeContainer.Lake.Builder builderForValue) {
        ensureLakesIsMutable();
        lakes_.set(index, builderForValue.build());

        return this;
      }
      /**
       * <code>repeated .Lake lakes = 1;</code>
       */
      public Builder addLakes(com.chunkmapper.protoc.LakeContainer.Lake value) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureLakesIsMutable();
        lakes_.add(value);

        return this;
      }
      /**
       * <code>repeated .Lake lakes = 1;</code>
       */
      public Builder addLakes(
          int index, com.chunkmapper.protoc.LakeContainer.Lake value) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureLakesIsMutable();
        lakes_.add(index, value);

        return this;
      }
      /**
       * <code>repeated .Lake lakes = 1;</code>
       */
      public Builder addLakes(
          com.chunkmapper.protoc.LakeContainer.Lake.Builder builderForValue) {
        ensureLakesIsMutable();
        lakes_.add(builderForValue.build());

        return this;
      }
      /**
       * <code>repeated .Lake lakes = 1;</code>
       */
      public Builder addLakes(
          int index, com.chunkmapper.protoc.LakeContainer.Lake.Builder builderForValue) {
        ensureLakesIsMutable();
        lakes_.add(index, builderForValue.build());

        return this;
      }
      /**
       * <code>repeated .Lake lakes = 1;</code>
       */
      public Builder addAllLakes(
          java.lang.Iterable<? extends com.chunkmapper.protoc.LakeContainer.Lake> values) {
        ensureLakesIsMutable();
        super.addAll(values, lakes_);

        return this;
      }
      /**
       * <code>repeated .Lake lakes = 1;</code>
       */
      public Builder clearLakes() {
        lakes_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000001);

        return this;
      }
      /**
       * <code>repeated .Lake lakes = 1;</code>
       */
      public Builder removeLakes(int index) {
        ensureLakesIsMutable();
        lakes_.remove(index);

        return this;
      }

      // @@protoc_insertion_point(builder_scope:LakeRegion)
    }

    static {
      defaultInstance = new LakeRegion(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:LakeRegion)
  }


  static {
  }

  // @@protoc_insertion_point(outer_class_scope)
}
