// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: POIContainer.proto

package com.chunkmapper.protoc;

public final class POIContainer {
  private POIContainer() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }
  public interface POIOrBuilder
      extends com.google.protobuf.MessageLiteOrBuilder {

    // required .Point point = 1;
    /**
     * <code>required .Point point = 1;</code>
     */
    boolean hasPoint();
    /**
     * <code>required .Point point = 1;</code>
     */
    com.chunkmapper.protoc.PointContainer.Point getPoint();

    // required string text = 2;
    /**
     * <code>required string text = 2;</code>
     */
    boolean hasText();
    /**
     * <code>required string text = 2;</code>
     */
    java.lang.String getText();
    /**
     * <code>required string text = 2;</code>
     */
    com.google.protobuf.ByteString
        getTextBytes();
  }
  /**
   * Protobuf type {@code POI}
   */
  public static final class POI extends
      com.google.protobuf.GeneratedMessageLite
      implements POIOrBuilder {
    // Use POI.newBuilder() to construct.
    private POI(com.google.protobuf.GeneratedMessageLite.Builder builder) {
      super(builder);

    }
    private POI(boolean noInit) {}

    private static final POI defaultInstance;
    public static POI getDefaultInstance() {
      return defaultInstance;
    }

    public POI getDefaultInstanceForType() {
      return defaultInstance;
    }

    private POI(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 10: {
              com.chunkmapper.protoc.PointContainer.Point.Builder subBuilder = null;
              if (((bitField0_ & 0x00000001) == 0x00000001)) {
                subBuilder = point_.toBuilder();
              }
              point_ = input.readMessage(com.chunkmapper.protoc.PointContainer.Point.PARSER, extensionRegistry);
              if (subBuilder != null) {
                subBuilder.mergeFrom(point_);
                point_ = subBuilder.buildPartial();
              }
              bitField0_ |= 0x00000001;
              break;
            }
            case 18: {
              bitField0_ |= 0x00000002;
              text_ = input.readBytes();
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        makeExtensionsImmutable();
      }
    }
    public static com.google.protobuf.Parser<POI> PARSER =
        new com.google.protobuf.AbstractParser<POI>() {
      public POI parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new POI(input, extensionRegistry);
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<POI> getParserForType() {
      return PARSER;
    }

    private int bitField0_;
    // required .Point point = 1;
    public static final int POINT_FIELD_NUMBER = 1;
    private com.chunkmapper.protoc.PointContainer.Point point_;
    /**
     * <code>required .Point point = 1;</code>
     */
    public boolean hasPoint() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>required .Point point = 1;</code>
     */
    public com.chunkmapper.protoc.PointContainer.Point getPoint() {
      return point_;
    }

    // required string text = 2;
    public static final int TEXT_FIELD_NUMBER = 2;
    private java.lang.Object text_;
    /**
     * <code>required string text = 2;</code>
     */
    public boolean hasText() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    /**
     * <code>required string text = 2;</code>
     */
    public java.lang.String getText() {
      java.lang.Object ref = text_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          text_ = s;
        }
        return s;
      }
    }
    /**
     * <code>required string text = 2;</code>
     */
    public com.google.protobuf.ByteString
        getTextBytes() {
      java.lang.Object ref = text_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        text_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    private void initFields() {
      point_ = com.chunkmapper.protoc.PointContainer.Point.getDefaultInstance();
      text_ = "";
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;

      if (!hasPoint()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasText()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!getPoint().isInitialized()) {
        memoizedIsInitialized = 0;
        return false;
      }
      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeMessage(1, point_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeBytes(2, getTextBytes());
      }
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(1, point_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(2, getTextBytes());
      }
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static com.chunkmapper.protoc.POIContainer.POI parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.chunkmapper.protoc.POIContainer.POI parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.chunkmapper.protoc.POIContainer.POI parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.chunkmapper.protoc.POIContainer.POI parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.chunkmapper.protoc.POIContainer.POI parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.chunkmapper.protoc.POIContainer.POI parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static com.chunkmapper.protoc.POIContainer.POI parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static com.chunkmapper.protoc.POIContainer.POI parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static com.chunkmapper.protoc.POIContainer.POI parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.chunkmapper.protoc.POIContainer.POI parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(com.chunkmapper.protoc.POIContainer.POI prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    /**
     * Protobuf type {@code POI}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageLite.Builder<
          com.chunkmapper.protoc.POIContainer.POI, Builder>
        implements com.chunkmapper.protoc.POIContainer.POIOrBuilder {
      // Construct using com.chunkmapper.protoc.POIContainer.POI.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private void maybeForceBuilderInitialization() {
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        point_ = com.chunkmapper.protoc.PointContainer.Point.getDefaultInstance();
        bitField0_ = (bitField0_ & ~0x00000001);
        text_ = "";
        bitField0_ = (bitField0_ & ~0x00000002);
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.chunkmapper.protoc.POIContainer.POI getDefaultInstanceForType() {
        return com.chunkmapper.protoc.POIContainer.POI.getDefaultInstance();
      }

      public com.chunkmapper.protoc.POIContainer.POI build() {
        com.chunkmapper.protoc.POIContainer.POI result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public com.chunkmapper.protoc.POIContainer.POI buildPartial() {
        com.chunkmapper.protoc.POIContainer.POI result = new com.chunkmapper.protoc.POIContainer.POI(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.point_ = point_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.text_ = text_;
        result.bitField0_ = to_bitField0_;
        return result;
      }

      public Builder mergeFrom(com.chunkmapper.protoc.POIContainer.POI other) {
        if (other == com.chunkmapper.protoc.POIContainer.POI.getDefaultInstance()) return this;
        if (other.hasPoint()) {
          mergePoint(other.getPoint());
        }
        if (other.hasText()) {
          bitField0_ |= 0x00000002;
          text_ = other.text_;
          
        }
        return this;
      }

      public final boolean isInitialized() {
        if (!hasPoint()) {
          
          return false;
        }
        if (!hasText()) {
          
          return false;
        }
        if (!getPoint().isInitialized()) {
          
          return false;
        }
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.chunkmapper.protoc.POIContainer.POI parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.chunkmapper.protoc.POIContainer.POI) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      // required .Point point = 1;
      private com.chunkmapper.protoc.PointContainer.Point point_ = com.chunkmapper.protoc.PointContainer.Point.getDefaultInstance();
      /**
       * <code>required .Point point = 1;</code>
       */
      public boolean hasPoint() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>required .Point point = 1;</code>
       */
      public com.chunkmapper.protoc.PointContainer.Point getPoint() {
        return point_;
      }
      /**
       * <code>required .Point point = 1;</code>
       */
      public Builder setPoint(com.chunkmapper.protoc.PointContainer.Point value) {
        if (value == null) {
          throw new NullPointerException();
        }
        point_ = value;

        bitField0_ |= 0x00000001;
        return this;
      }
      /**
       * <code>required .Point point = 1;</code>
       */
      public Builder setPoint(
          com.chunkmapper.protoc.PointContainer.Point.Builder builderForValue) {
        point_ = builderForValue.build();

        bitField0_ |= 0x00000001;
        return this;
      }
      /**
       * <code>required .Point point = 1;</code>
       */
      public Builder mergePoint(com.chunkmapper.protoc.PointContainer.Point value) {
        if (((bitField0_ & 0x00000001) == 0x00000001) &&
            point_ != com.chunkmapper.protoc.PointContainer.Point.getDefaultInstance()) {
          point_ =
            com.chunkmapper.protoc.PointContainer.Point.newBuilder(point_).mergeFrom(value).buildPartial();
        } else {
          point_ = value;
        }

        bitField0_ |= 0x00000001;
        return this;
      }
      /**
       * <code>required .Point point = 1;</code>
       */
      public Builder clearPoint() {
        point_ = com.chunkmapper.protoc.PointContainer.Point.getDefaultInstance();

        bitField0_ = (bitField0_ & ~0x00000001);
        return this;
      }

      // required string text = 2;
      private java.lang.Object text_ = "";
      /**
       * <code>required string text = 2;</code>
       */
      public boolean hasText() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      /**
       * <code>required string text = 2;</code>
       */
      public java.lang.String getText() {
        java.lang.Object ref = text_;
        if (!(ref instanceof java.lang.String)) {
          java.lang.String s = ((com.google.protobuf.ByteString) ref)
              .toStringUtf8();
          text_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>required string text = 2;</code>
       */
      public com.google.protobuf.ByteString
          getTextBytes() {
        java.lang.Object ref = text_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          text_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>required string text = 2;</code>
       */
      public Builder setText(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
        text_ = value;
        
        return this;
      }
      /**
       * <code>required string text = 2;</code>
       */
      public Builder clearText() {
        bitField0_ = (bitField0_ & ~0x00000002);
        text_ = getDefaultInstance().getText();
        
        return this;
      }
      /**
       * <code>required string text = 2;</code>
       */
      public Builder setTextBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
        text_ = value;
        
        return this;
      }

      // @@protoc_insertion_point(builder_scope:POI)
    }

    static {
      defaultInstance = new POI(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:POI)
  }

  public interface POIRegionOrBuilder
      extends com.google.protobuf.MessageLiteOrBuilder {

    // repeated .POI pois = 1;
    /**
     * <code>repeated .POI pois = 1;</code>
     */
    java.util.List<com.chunkmapper.protoc.POIContainer.POI> 
        getPoisList();
    /**
     * <code>repeated .POI pois = 1;</code>
     */
    com.chunkmapper.protoc.POIContainer.POI getPois(int index);
    /**
     * <code>repeated .POI pois = 1;</code>
     */
    int getPoisCount();
  }
  /**
   * Protobuf type {@code POIRegion}
   */
  public static final class POIRegion extends
      com.google.protobuf.GeneratedMessageLite
      implements POIRegionOrBuilder {
    // Use POIRegion.newBuilder() to construct.
    private POIRegion(com.google.protobuf.GeneratedMessageLite.Builder builder) {
      super(builder);

    }
    private POIRegion(boolean noInit) {}

    private static final POIRegion defaultInstance;
    public static POIRegion getDefaultInstance() {
      return defaultInstance;
    }

    public POIRegion getDefaultInstanceForType() {
      return defaultInstance;
    }

    private POIRegion(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 10: {
              if (!((mutable_bitField0_ & 0x00000001) == 0x00000001)) {
                pois_ = new java.util.ArrayList<com.chunkmapper.protoc.POIContainer.POI>();
                mutable_bitField0_ |= 0x00000001;
              }
              pois_.add(input.readMessage(com.chunkmapper.protoc.POIContainer.POI.PARSER, extensionRegistry));
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        if (((mutable_bitField0_ & 0x00000001) == 0x00000001)) {
          pois_ = java.util.Collections.unmodifiableList(pois_);
        }
        makeExtensionsImmutable();
      }
    }
    public static com.google.protobuf.Parser<POIRegion> PARSER =
        new com.google.protobuf.AbstractParser<POIRegion>() {
      public POIRegion parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new POIRegion(input, extensionRegistry);
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<POIRegion> getParserForType() {
      return PARSER;
    }

    // repeated .POI pois = 1;
    public static final int POIS_FIELD_NUMBER = 1;
    private java.util.List<com.chunkmapper.protoc.POIContainer.POI> pois_;
    /**
     * <code>repeated .POI pois = 1;</code>
     */
    public java.util.List<com.chunkmapper.protoc.POIContainer.POI> getPoisList() {
      return pois_;
    }
    /**
     * <code>repeated .POI pois = 1;</code>
     */
    public java.util.List<? extends com.chunkmapper.protoc.POIContainer.POIOrBuilder> 
        getPoisOrBuilderList() {
      return pois_;
    }
    /**
     * <code>repeated .POI pois = 1;</code>
     */
    public int getPoisCount() {
      return pois_.size();
    }
    /**
     * <code>repeated .POI pois = 1;</code>
     */
    public com.chunkmapper.protoc.POIContainer.POI getPois(int index) {
      return pois_.get(index);
    }
    /**
     * <code>repeated .POI pois = 1;</code>
     */
    public com.chunkmapper.protoc.POIContainer.POIOrBuilder getPoisOrBuilder(
        int index) {
      return pois_.get(index);
    }

    private void initFields() {
      pois_ = java.util.Collections.emptyList();
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;

      for (int i = 0; i < getPoisCount(); i++) {
        if (!getPois(i).isInitialized()) {
          memoizedIsInitialized = 0;
          return false;
        }
      }
      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      for (int i = 0; i < pois_.size(); i++) {
        output.writeMessage(1, pois_.get(i));
      }
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      for (int i = 0; i < pois_.size(); i++) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(1, pois_.get(i));
      }
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static com.chunkmapper.protoc.POIContainer.POIRegion parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.chunkmapper.protoc.POIContainer.POIRegion parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.chunkmapper.protoc.POIContainer.POIRegion parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.chunkmapper.protoc.POIContainer.POIRegion parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.chunkmapper.protoc.POIContainer.POIRegion parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.chunkmapper.protoc.POIContainer.POIRegion parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static com.chunkmapper.protoc.POIContainer.POIRegion parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static com.chunkmapper.protoc.POIContainer.POIRegion parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static com.chunkmapper.protoc.POIContainer.POIRegion parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.chunkmapper.protoc.POIContainer.POIRegion parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(com.chunkmapper.protoc.POIContainer.POIRegion prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    /**
     * Protobuf type {@code POIRegion}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageLite.Builder<
          com.chunkmapper.protoc.POIContainer.POIRegion, Builder>
        implements com.chunkmapper.protoc.POIContainer.POIRegionOrBuilder {
      // Construct using com.chunkmapper.protoc.POIContainer.POIRegion.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private void maybeForceBuilderInitialization() {
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        pois_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000001);
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.chunkmapper.protoc.POIContainer.POIRegion getDefaultInstanceForType() {
        return com.chunkmapper.protoc.POIContainer.POIRegion.getDefaultInstance();
      }

      public com.chunkmapper.protoc.POIContainer.POIRegion build() {
        com.chunkmapper.protoc.POIContainer.POIRegion result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public com.chunkmapper.protoc.POIContainer.POIRegion buildPartial() {
        com.chunkmapper.protoc.POIContainer.POIRegion result = new com.chunkmapper.protoc.POIContainer.POIRegion(this);
        int from_bitField0_ = bitField0_;
        if (((bitField0_ & 0x00000001) == 0x00000001)) {
          pois_ = java.util.Collections.unmodifiableList(pois_);
          bitField0_ = (bitField0_ & ~0x00000001);
        }
        result.pois_ = pois_;
        return result;
      }

      public Builder mergeFrom(com.chunkmapper.protoc.POIContainer.POIRegion other) {
        if (other == com.chunkmapper.protoc.POIContainer.POIRegion.getDefaultInstance()) return this;
        if (!other.pois_.isEmpty()) {
          if (pois_.isEmpty()) {
            pois_ = other.pois_;
            bitField0_ = (bitField0_ & ~0x00000001);
          } else {
            ensurePoisIsMutable();
            pois_.addAll(other.pois_);
          }
          
        }
        return this;
      }

      public final boolean isInitialized() {
        for (int i = 0; i < getPoisCount(); i++) {
          if (!getPois(i).isInitialized()) {
            
            return false;
          }
        }
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.chunkmapper.protoc.POIContainer.POIRegion parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.chunkmapper.protoc.POIContainer.POIRegion) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      // repeated .POI pois = 1;
      private java.util.List<com.chunkmapper.protoc.POIContainer.POI> pois_ =
        java.util.Collections.emptyList();
      private void ensurePoisIsMutable() {
        if (!((bitField0_ & 0x00000001) == 0x00000001)) {
          pois_ = new java.util.ArrayList<com.chunkmapper.protoc.POIContainer.POI>(pois_);
          bitField0_ |= 0x00000001;
         }
      }

      /**
       * <code>repeated .POI pois = 1;</code>
       */
      public java.util.List<com.chunkmapper.protoc.POIContainer.POI> getPoisList() {
        return java.util.Collections.unmodifiableList(pois_);
      }
      /**
       * <code>repeated .POI pois = 1;</code>
       */
      public int getPoisCount() {
        return pois_.size();
      }
      /**
       * <code>repeated .POI pois = 1;</code>
       */
      public com.chunkmapper.protoc.POIContainer.POI getPois(int index) {
        return pois_.get(index);
      }
      /**
       * <code>repeated .POI pois = 1;</code>
       */
      public Builder setPois(
          int index, com.chunkmapper.protoc.POIContainer.POI value) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensurePoisIsMutable();
        pois_.set(index, value);

        return this;
      }
      /**
       * <code>repeated .POI pois = 1;</code>
       */
      public Builder setPois(
          int index, com.chunkmapper.protoc.POIContainer.POI.Builder builderForValue) {
        ensurePoisIsMutable();
        pois_.set(index, builderForValue.build());

        return this;
      }
      /**
       * <code>repeated .POI pois = 1;</code>
       */
      public Builder addPois(com.chunkmapper.protoc.POIContainer.POI value) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensurePoisIsMutable();
        pois_.add(value);

        return this;
      }
      /**
       * <code>repeated .POI pois = 1;</code>
       */
      public Builder addPois(
          int index, com.chunkmapper.protoc.POIContainer.POI value) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensurePoisIsMutable();
        pois_.add(index, value);

        return this;
      }
      /**
       * <code>repeated .POI pois = 1;</code>
       */
      public Builder addPois(
          com.chunkmapper.protoc.POIContainer.POI.Builder builderForValue) {
        ensurePoisIsMutable();
        pois_.add(builderForValue.build());

        return this;
      }
      /**
       * <code>repeated .POI pois = 1;</code>
       */
      public Builder addPois(
          int index, com.chunkmapper.protoc.POIContainer.POI.Builder builderForValue) {
        ensurePoisIsMutable();
        pois_.add(index, builderForValue.build());

        return this;
      }
      /**
       * <code>repeated .POI pois = 1;</code>
       */
      public Builder addAllPois(
          java.lang.Iterable<? extends com.chunkmapper.protoc.POIContainer.POI> values) {
        ensurePoisIsMutable();
        super.addAll(values, pois_);

        return this;
      }
      /**
       * <code>repeated .POI pois = 1;</code>
       */
      public Builder clearPois() {
        pois_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000001);

        return this;
      }
      /**
       * <code>repeated .POI pois = 1;</code>
       */
      public Builder removePois(int index) {
        ensurePoisIsMutable();
        pois_.remove(index);

        return this;
      }

      // @@protoc_insertion_point(builder_scope:POIRegion)
    }

    static {
      defaultInstance = new POIRegion(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:POIRegion)
  }


  static {
  }

  // @@protoc_insertion_point(outer_class_scope)
}
