// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: PATH/ServerInfoContainer.proto

package com.chunkmapper.protoc;

public final class ServerInfoContainer {
  private ServerInfoContainer() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
  }
  public interface ServerInfoOrBuilder
      extends com.google.protobuf.MessageOrBuilder {

    // optional string rail_address = 1;
    /**
     * <code>optional string rail_address = 1;</code>
     */
    boolean hasRailAddress();
    /**
     * <code>optional string rail_address = 1;</code>
     */
    java.lang.String getRailAddress();
    /**
     * <code>optional string rail_address = 1;</code>
     */
    com.google.protobuf.ByteString
        getRailAddressBytes();

    // optional string river_address = 2;
    /**
     * <code>optional string river_address = 2;</code>
     */
    boolean hasRiverAddress();
    /**
     * <code>optional string river_address = 2;</code>
     */
    java.lang.String getRiverAddress();
    /**
     * <code>optional string river_address = 2;</code>
     */
    com.google.protobuf.ByteString
        getRiverAddressBytes();

    // optional string lake_address = 3;
    /**
     * <code>optional string lake_address = 3;</code>
     */
    boolean hasLakeAddress();
    /**
     * <code>optional string lake_address = 3;</code>
     */
    java.lang.String getLakeAddress();
    /**
     * <code>optional string lake_address = 3;</code>
     */
    com.google.protobuf.ByteString
        getLakeAddressBytes();

    // optional string coastline_address = 4;
    /**
     * <code>optional string coastline_address = 4;</code>
     */
    boolean hasCoastlineAddress();
    /**
     * <code>optional string coastline_address = 4;</code>
     */
    java.lang.String getCoastlineAddress();
    /**
     * <code>optional string coastline_address = 4;</code>
     */
    com.google.protobuf.ByteString
        getCoastlineAddressBytes();

    // optional string poi_address = 5;
    /**
     * <code>optional string poi_address = 5;</code>
     */
    boolean hasPoiAddress();
    /**
     * <code>optional string poi_address = 5;</code>
     */
    java.lang.String getPoiAddress();
    /**
     * <code>optional string poi_address = 5;</code>
     */
    com.google.protobuf.ByteString
        getPoiAddressBytes();

    // optional string globcover_address = 6;
    /**
     * <code>optional string globcover_address = 6;</code>
     */
    boolean hasGlobcoverAddress();
    /**
     * <code>optional string globcover_address = 6;</code>
     */
    java.lang.String getGlobcoverAddress();
    /**
     * <code>optional string globcover_address = 6;</code>
     */
    com.google.protobuf.ByteString
        getGlobcoverAddressBytes();

    // optional bool get_xapi = 7;
    /**
     * <code>optional bool get_xapi = 7;</code>
     */
    boolean hasGetXapi();
    /**
     * <code>optional bool get_xapi = 7;</code>
     */
    boolean getGetXapi();

    // optional string reset_password_address = 8;
    /**
     * <code>optional string reset_password_address = 8;</code>
     */
    boolean hasResetPasswordAddress();
    /**
     * <code>optional string reset_password_address = 8;</code>
     */
    java.lang.String getResetPasswordAddress();
    /**
     * <code>optional string reset_password_address = 8;</code>
     */
    com.google.protobuf.ByteString
        getResetPasswordAddressBytes();
  }
  /**
   * Protobuf type {@code ServerInfo}
   */
  public static final class ServerInfo extends
      com.google.protobuf.GeneratedMessage
      implements ServerInfoOrBuilder {
    // Use ServerInfo.newBuilder() to construct.
    private ServerInfo(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private ServerInfo(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final ServerInfo defaultInstance;
    public static ServerInfo getDefaultInstance() {
      return defaultInstance;
    }

    public ServerInfo getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private ServerInfo(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 10: {
              bitField0_ |= 0x00000001;
              railAddress_ = input.readBytes();
              break;
            }
            case 18: {
              bitField0_ |= 0x00000002;
              riverAddress_ = input.readBytes();
              break;
            }
            case 26: {
              bitField0_ |= 0x00000004;
              lakeAddress_ = input.readBytes();
              break;
            }
            case 34: {
              bitField0_ |= 0x00000008;
              coastlineAddress_ = input.readBytes();
              break;
            }
            case 42: {
              bitField0_ |= 0x00000010;
              poiAddress_ = input.readBytes();
              break;
            }
            case 50: {
              bitField0_ |= 0x00000020;
              globcoverAddress_ = input.readBytes();
              break;
            }
            case 56: {
              bitField0_ |= 0x00000040;
              getXapi_ = input.readBool();
              break;
            }
            case 66: {
              bitField0_ |= 0x00000080;
              resetPasswordAddress_ = input.readBytes();
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.chunkmapper.protoc.ServerInfoContainer.internal_static_ServerInfo_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.chunkmapper.protoc.ServerInfoContainer.internal_static_ServerInfo_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.chunkmapper.protoc.ServerInfoContainer.ServerInfo.class, com.chunkmapper.protoc.ServerInfoContainer.ServerInfo.Builder.class);
    }

    public static com.google.protobuf.Parser<ServerInfo> PARSER =
        new com.google.protobuf.AbstractParser<ServerInfo>() {
      public ServerInfo parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new ServerInfo(input, extensionRegistry);
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<ServerInfo> getParserForType() {
      return PARSER;
    }

    private int bitField0_;
    // optional string rail_address = 1;
    public static final int RAIL_ADDRESS_FIELD_NUMBER = 1;
    private java.lang.Object railAddress_;
    /**
     * <code>optional string rail_address = 1;</code>
     */
    public boolean hasRailAddress() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>optional string rail_address = 1;</code>
     */
    public java.lang.String getRailAddress() {
      java.lang.Object ref = railAddress_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          railAddress_ = s;
        }
        return s;
      }
    }
    /**
     * <code>optional string rail_address = 1;</code>
     */
    public com.google.protobuf.ByteString
        getRailAddressBytes() {
      java.lang.Object ref = railAddress_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        railAddress_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    // optional string river_address = 2;
    public static final int RIVER_ADDRESS_FIELD_NUMBER = 2;
    private java.lang.Object riverAddress_;
    /**
     * <code>optional string river_address = 2;</code>
     */
    public boolean hasRiverAddress() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    /**
     * <code>optional string river_address = 2;</code>
     */
    public java.lang.String getRiverAddress() {
      java.lang.Object ref = riverAddress_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          riverAddress_ = s;
        }
        return s;
      }
    }
    /**
     * <code>optional string river_address = 2;</code>
     */
    public com.google.protobuf.ByteString
        getRiverAddressBytes() {
      java.lang.Object ref = riverAddress_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        riverAddress_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    // optional string lake_address = 3;
    public static final int LAKE_ADDRESS_FIELD_NUMBER = 3;
    private java.lang.Object lakeAddress_;
    /**
     * <code>optional string lake_address = 3;</code>
     */
    public boolean hasLakeAddress() {
      return ((bitField0_ & 0x00000004) == 0x00000004);
    }
    /**
     * <code>optional string lake_address = 3;</code>
     */
    public java.lang.String getLakeAddress() {
      java.lang.Object ref = lakeAddress_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          lakeAddress_ = s;
        }
        return s;
      }
    }
    /**
     * <code>optional string lake_address = 3;</code>
     */
    public com.google.protobuf.ByteString
        getLakeAddressBytes() {
      java.lang.Object ref = lakeAddress_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        lakeAddress_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    // optional string coastline_address = 4;
    public static final int COASTLINE_ADDRESS_FIELD_NUMBER = 4;
    private java.lang.Object coastlineAddress_;
    /**
     * <code>optional string coastline_address = 4;</code>
     */
    public boolean hasCoastlineAddress() {
      return ((bitField0_ & 0x00000008) == 0x00000008);
    }
    /**
     * <code>optional string coastline_address = 4;</code>
     */
    public java.lang.String getCoastlineAddress() {
      java.lang.Object ref = coastlineAddress_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          coastlineAddress_ = s;
        }
        return s;
      }
    }
    /**
     * <code>optional string coastline_address = 4;</code>
     */
    public com.google.protobuf.ByteString
        getCoastlineAddressBytes() {
      java.lang.Object ref = coastlineAddress_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        coastlineAddress_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    // optional string poi_address = 5;
    public static final int POI_ADDRESS_FIELD_NUMBER = 5;
    private java.lang.Object poiAddress_;
    /**
     * <code>optional string poi_address = 5;</code>
     */
    public boolean hasPoiAddress() {
      return ((bitField0_ & 0x00000010) == 0x00000010);
    }
    /**
     * <code>optional string poi_address = 5;</code>
     */
    public java.lang.String getPoiAddress() {
      java.lang.Object ref = poiAddress_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          poiAddress_ = s;
        }
        return s;
      }
    }
    /**
     * <code>optional string poi_address = 5;</code>
     */
    public com.google.protobuf.ByteString
        getPoiAddressBytes() {
      java.lang.Object ref = poiAddress_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        poiAddress_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    // optional string globcover_address = 6;
    public static final int GLOBCOVER_ADDRESS_FIELD_NUMBER = 6;
    private java.lang.Object globcoverAddress_;
    /**
     * <code>optional string globcover_address = 6;</code>
     */
    public boolean hasGlobcoverAddress() {
      return ((bitField0_ & 0x00000020) == 0x00000020);
    }
    /**
     * <code>optional string globcover_address = 6;</code>
     */
    public java.lang.String getGlobcoverAddress() {
      java.lang.Object ref = globcoverAddress_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          globcoverAddress_ = s;
        }
        return s;
      }
    }
    /**
     * <code>optional string globcover_address = 6;</code>
     */
    public com.google.protobuf.ByteString
        getGlobcoverAddressBytes() {
      java.lang.Object ref = globcoverAddress_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        globcoverAddress_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    // optional bool get_xapi = 7;
    public static final int GET_XAPI_FIELD_NUMBER = 7;
    private boolean getXapi_;
    /**
     * <code>optional bool get_xapi = 7;</code>
     */
    public boolean hasGetXapi() {
      return ((bitField0_ & 0x00000040) == 0x00000040);
    }
    /**
     * <code>optional bool get_xapi = 7;</code>
     */
    public boolean getGetXapi() {
      return getXapi_;
    }

    // optional string reset_password_address = 8;
    public static final int RESET_PASSWORD_ADDRESS_FIELD_NUMBER = 8;
    private java.lang.Object resetPasswordAddress_;
    /**
     * <code>optional string reset_password_address = 8;</code>
     */
    public boolean hasResetPasswordAddress() {
      return ((bitField0_ & 0x00000080) == 0x00000080);
    }
    /**
     * <code>optional string reset_password_address = 8;</code>
     */
    public java.lang.String getResetPasswordAddress() {
      java.lang.Object ref = resetPasswordAddress_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          resetPasswordAddress_ = s;
        }
        return s;
      }
    }
    /**
     * <code>optional string reset_password_address = 8;</code>
     */
    public com.google.protobuf.ByteString
        getResetPasswordAddressBytes() {
      java.lang.Object ref = resetPasswordAddress_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        resetPasswordAddress_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    private void initFields() {
      railAddress_ = "";
      riverAddress_ = "";
      lakeAddress_ = "";
      coastlineAddress_ = "";
      poiAddress_ = "";
      globcoverAddress_ = "";
      getXapi_ = false;
      resetPasswordAddress_ = "";
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeBytes(1, getRailAddressBytes());
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeBytes(2, getRiverAddressBytes());
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        output.writeBytes(3, getLakeAddressBytes());
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        output.writeBytes(4, getCoastlineAddressBytes());
      }
      if (((bitField0_ & 0x00000010) == 0x00000010)) {
        output.writeBytes(5, getPoiAddressBytes());
      }
      if (((bitField0_ & 0x00000020) == 0x00000020)) {
        output.writeBytes(6, getGlobcoverAddressBytes());
      }
      if (((bitField0_ & 0x00000040) == 0x00000040)) {
        output.writeBool(7, getXapi_);
      }
      if (((bitField0_ & 0x00000080) == 0x00000080)) {
        output.writeBytes(8, getResetPasswordAddressBytes());
      }
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(1, getRailAddressBytes());
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(2, getRiverAddressBytes());
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(3, getLakeAddressBytes());
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(4, getCoastlineAddressBytes());
      }
      if (((bitField0_ & 0x00000010) == 0x00000010)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(5, getPoiAddressBytes());
      }
      if (((bitField0_ & 0x00000020) == 0x00000020)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(6, getGlobcoverAddressBytes());
      }
      if (((bitField0_ & 0x00000040) == 0x00000040)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBoolSize(7, getXapi_);
      }
      if (((bitField0_ & 0x00000080) == 0x00000080)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(8, getResetPasswordAddressBytes());
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static com.chunkmapper.protoc.ServerInfoContainer.ServerInfo parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.chunkmapper.protoc.ServerInfoContainer.ServerInfo parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.chunkmapper.protoc.ServerInfoContainer.ServerInfo parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.chunkmapper.protoc.ServerInfoContainer.ServerInfo parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.chunkmapper.protoc.ServerInfoContainer.ServerInfo parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.chunkmapper.protoc.ServerInfoContainer.ServerInfo parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static com.chunkmapper.protoc.ServerInfoContainer.ServerInfo parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static com.chunkmapper.protoc.ServerInfoContainer.ServerInfo parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static com.chunkmapper.protoc.ServerInfoContainer.ServerInfo parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.chunkmapper.protoc.ServerInfoContainer.ServerInfo parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(com.chunkmapper.protoc.ServerInfoContainer.ServerInfo prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code ServerInfo}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements com.chunkmapper.protoc.ServerInfoContainer.ServerInfoOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.chunkmapper.protoc.ServerInfoContainer.internal_static_ServerInfo_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.chunkmapper.protoc.ServerInfoContainer.internal_static_ServerInfo_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.chunkmapper.protoc.ServerInfoContainer.ServerInfo.class, com.chunkmapper.protoc.ServerInfoContainer.ServerInfo.Builder.class);
      }

      // Construct using com.chunkmapper.protoc.ServerInfoContainer.ServerInfo.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        railAddress_ = "";
        bitField0_ = (bitField0_ & ~0x00000001);
        riverAddress_ = "";
        bitField0_ = (bitField0_ & ~0x00000002);
        lakeAddress_ = "";
        bitField0_ = (bitField0_ & ~0x00000004);
        coastlineAddress_ = "";
        bitField0_ = (bitField0_ & ~0x00000008);
        poiAddress_ = "";
        bitField0_ = (bitField0_ & ~0x00000010);
        globcoverAddress_ = "";
        bitField0_ = (bitField0_ & ~0x00000020);
        getXapi_ = false;
        bitField0_ = (bitField0_ & ~0x00000040);
        resetPasswordAddress_ = "";
        bitField0_ = (bitField0_ & ~0x00000080);
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.chunkmapper.protoc.ServerInfoContainer.internal_static_ServerInfo_descriptor;
      }

      public com.chunkmapper.protoc.ServerInfoContainer.ServerInfo getDefaultInstanceForType() {
        return com.chunkmapper.protoc.ServerInfoContainer.ServerInfo.getDefaultInstance();
      }

      public com.chunkmapper.protoc.ServerInfoContainer.ServerInfo build() {
        com.chunkmapper.protoc.ServerInfoContainer.ServerInfo result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public com.chunkmapper.protoc.ServerInfoContainer.ServerInfo buildPartial() {
        com.chunkmapper.protoc.ServerInfoContainer.ServerInfo result = new com.chunkmapper.protoc.ServerInfoContainer.ServerInfo(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.railAddress_ = railAddress_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.riverAddress_ = riverAddress_;
        if (((from_bitField0_ & 0x00000004) == 0x00000004)) {
          to_bitField0_ |= 0x00000004;
        }
        result.lakeAddress_ = lakeAddress_;
        if (((from_bitField0_ & 0x00000008) == 0x00000008)) {
          to_bitField0_ |= 0x00000008;
        }
        result.coastlineAddress_ = coastlineAddress_;
        if (((from_bitField0_ & 0x00000010) == 0x00000010)) {
          to_bitField0_ |= 0x00000010;
        }
        result.poiAddress_ = poiAddress_;
        if (((from_bitField0_ & 0x00000020) == 0x00000020)) {
          to_bitField0_ |= 0x00000020;
        }
        result.globcoverAddress_ = globcoverAddress_;
        if (((from_bitField0_ & 0x00000040) == 0x00000040)) {
          to_bitField0_ |= 0x00000040;
        }
        result.getXapi_ = getXapi_;
        if (((from_bitField0_ & 0x00000080) == 0x00000080)) {
          to_bitField0_ |= 0x00000080;
        }
        result.resetPasswordAddress_ = resetPasswordAddress_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.chunkmapper.protoc.ServerInfoContainer.ServerInfo) {
          return mergeFrom((com.chunkmapper.protoc.ServerInfoContainer.ServerInfo)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.chunkmapper.protoc.ServerInfoContainer.ServerInfo other) {
        if (other == com.chunkmapper.protoc.ServerInfoContainer.ServerInfo.getDefaultInstance()) return this;
        if (other.hasRailAddress()) {
          bitField0_ |= 0x00000001;
          railAddress_ = other.railAddress_;
          onChanged();
        }
        if (other.hasRiverAddress()) {
          bitField0_ |= 0x00000002;
          riverAddress_ = other.riverAddress_;
          onChanged();
        }
        if (other.hasLakeAddress()) {
          bitField0_ |= 0x00000004;
          lakeAddress_ = other.lakeAddress_;
          onChanged();
        }
        if (other.hasCoastlineAddress()) {
          bitField0_ |= 0x00000008;
          coastlineAddress_ = other.coastlineAddress_;
          onChanged();
        }
        if (other.hasPoiAddress()) {
          bitField0_ |= 0x00000010;
          poiAddress_ = other.poiAddress_;
          onChanged();
        }
        if (other.hasGlobcoverAddress()) {
          bitField0_ |= 0x00000020;
          globcoverAddress_ = other.globcoverAddress_;
          onChanged();
        }
        if (other.hasGetXapi()) {
          setGetXapi(other.getGetXapi());
        }
        if (other.hasResetPasswordAddress()) {
          bitField0_ |= 0x00000080;
          resetPasswordAddress_ = other.resetPasswordAddress_;
          onChanged();
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.chunkmapper.protoc.ServerInfoContainer.ServerInfo parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.chunkmapper.protoc.ServerInfoContainer.ServerInfo) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      // optional string rail_address = 1;
      private java.lang.Object railAddress_ = "";
      /**
       * <code>optional string rail_address = 1;</code>
       */
      public boolean hasRailAddress() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>optional string rail_address = 1;</code>
       */
      public java.lang.String getRailAddress() {
        java.lang.Object ref = railAddress_;
        if (!(ref instanceof java.lang.String)) {
          java.lang.String s = ((com.google.protobuf.ByteString) ref)
              .toStringUtf8();
          railAddress_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>optional string rail_address = 1;</code>
       */
      public com.google.protobuf.ByteString
          getRailAddressBytes() {
        java.lang.Object ref = railAddress_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          railAddress_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string rail_address = 1;</code>
       */
      public Builder setRailAddress(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        railAddress_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string rail_address = 1;</code>
       */
      public Builder clearRailAddress() {
        bitField0_ = (bitField0_ & ~0x00000001);
        railAddress_ = getDefaultInstance().getRailAddress();
        onChanged();
        return this;
      }
      /**
       * <code>optional string rail_address = 1;</code>
       */
      public Builder setRailAddressBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        railAddress_ = value;
        onChanged();
        return this;
      }

      // optional string river_address = 2;
      private java.lang.Object riverAddress_ = "";
      /**
       * <code>optional string river_address = 2;</code>
       */
      public boolean hasRiverAddress() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      /**
       * <code>optional string river_address = 2;</code>
       */
      public java.lang.String getRiverAddress() {
        java.lang.Object ref = riverAddress_;
        if (!(ref instanceof java.lang.String)) {
          java.lang.String s = ((com.google.protobuf.ByteString) ref)
              .toStringUtf8();
          riverAddress_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>optional string river_address = 2;</code>
       */
      public com.google.protobuf.ByteString
          getRiverAddressBytes() {
        java.lang.Object ref = riverAddress_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          riverAddress_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string river_address = 2;</code>
       */
      public Builder setRiverAddress(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
        riverAddress_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string river_address = 2;</code>
       */
      public Builder clearRiverAddress() {
        bitField0_ = (bitField0_ & ~0x00000002);
        riverAddress_ = getDefaultInstance().getRiverAddress();
        onChanged();
        return this;
      }
      /**
       * <code>optional string river_address = 2;</code>
       */
      public Builder setRiverAddressBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
        riverAddress_ = value;
        onChanged();
        return this;
      }

      // optional string lake_address = 3;
      private java.lang.Object lakeAddress_ = "";
      /**
       * <code>optional string lake_address = 3;</code>
       */
      public boolean hasLakeAddress() {
        return ((bitField0_ & 0x00000004) == 0x00000004);
      }
      /**
       * <code>optional string lake_address = 3;</code>
       */
      public java.lang.String getLakeAddress() {
        java.lang.Object ref = lakeAddress_;
        if (!(ref instanceof java.lang.String)) {
          java.lang.String s = ((com.google.protobuf.ByteString) ref)
              .toStringUtf8();
          lakeAddress_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>optional string lake_address = 3;</code>
       */
      public com.google.protobuf.ByteString
          getLakeAddressBytes() {
        java.lang.Object ref = lakeAddress_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          lakeAddress_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string lake_address = 3;</code>
       */
      public Builder setLakeAddress(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000004;
        lakeAddress_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string lake_address = 3;</code>
       */
      public Builder clearLakeAddress() {
        bitField0_ = (bitField0_ & ~0x00000004);
        lakeAddress_ = getDefaultInstance().getLakeAddress();
        onChanged();
        return this;
      }
      /**
       * <code>optional string lake_address = 3;</code>
       */
      public Builder setLakeAddressBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000004;
        lakeAddress_ = value;
        onChanged();
        return this;
      }

      // optional string coastline_address = 4;
      private java.lang.Object coastlineAddress_ = "";
      /**
       * <code>optional string coastline_address = 4;</code>
       */
      public boolean hasCoastlineAddress() {
        return ((bitField0_ & 0x00000008) == 0x00000008);
      }
      /**
       * <code>optional string coastline_address = 4;</code>
       */
      public java.lang.String getCoastlineAddress() {
        java.lang.Object ref = coastlineAddress_;
        if (!(ref instanceof java.lang.String)) {
          java.lang.String s = ((com.google.protobuf.ByteString) ref)
              .toStringUtf8();
          coastlineAddress_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>optional string coastline_address = 4;</code>
       */
      public com.google.protobuf.ByteString
          getCoastlineAddressBytes() {
        java.lang.Object ref = coastlineAddress_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          coastlineAddress_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string coastline_address = 4;</code>
       */
      public Builder setCoastlineAddress(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000008;
        coastlineAddress_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string coastline_address = 4;</code>
       */
      public Builder clearCoastlineAddress() {
        bitField0_ = (bitField0_ & ~0x00000008);
        coastlineAddress_ = getDefaultInstance().getCoastlineAddress();
        onChanged();
        return this;
      }
      /**
       * <code>optional string coastline_address = 4;</code>
       */
      public Builder setCoastlineAddressBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000008;
        coastlineAddress_ = value;
        onChanged();
        return this;
      }

      // optional string poi_address = 5;
      private java.lang.Object poiAddress_ = "";
      /**
       * <code>optional string poi_address = 5;</code>
       */
      public boolean hasPoiAddress() {
        return ((bitField0_ & 0x00000010) == 0x00000010);
      }
      /**
       * <code>optional string poi_address = 5;</code>
       */
      public java.lang.String getPoiAddress() {
        java.lang.Object ref = poiAddress_;
        if (!(ref instanceof java.lang.String)) {
          java.lang.String s = ((com.google.protobuf.ByteString) ref)
              .toStringUtf8();
          poiAddress_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>optional string poi_address = 5;</code>
       */
      public com.google.protobuf.ByteString
          getPoiAddressBytes() {
        java.lang.Object ref = poiAddress_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          poiAddress_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string poi_address = 5;</code>
       */
      public Builder setPoiAddress(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000010;
        poiAddress_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string poi_address = 5;</code>
       */
      public Builder clearPoiAddress() {
        bitField0_ = (bitField0_ & ~0x00000010);
        poiAddress_ = getDefaultInstance().getPoiAddress();
        onChanged();
        return this;
      }
      /**
       * <code>optional string poi_address = 5;</code>
       */
      public Builder setPoiAddressBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000010;
        poiAddress_ = value;
        onChanged();
        return this;
      }

      // optional string globcover_address = 6;
      private java.lang.Object globcoverAddress_ = "";
      /**
       * <code>optional string globcover_address = 6;</code>
       */
      public boolean hasGlobcoverAddress() {
        return ((bitField0_ & 0x00000020) == 0x00000020);
      }
      /**
       * <code>optional string globcover_address = 6;</code>
       */
      public java.lang.String getGlobcoverAddress() {
        java.lang.Object ref = globcoverAddress_;
        if (!(ref instanceof java.lang.String)) {
          java.lang.String s = ((com.google.protobuf.ByteString) ref)
              .toStringUtf8();
          globcoverAddress_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>optional string globcover_address = 6;</code>
       */
      public com.google.protobuf.ByteString
          getGlobcoverAddressBytes() {
        java.lang.Object ref = globcoverAddress_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          globcoverAddress_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string globcover_address = 6;</code>
       */
      public Builder setGlobcoverAddress(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000020;
        globcoverAddress_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string globcover_address = 6;</code>
       */
      public Builder clearGlobcoverAddress() {
        bitField0_ = (bitField0_ & ~0x00000020);
        globcoverAddress_ = getDefaultInstance().getGlobcoverAddress();
        onChanged();
        return this;
      }
      /**
       * <code>optional string globcover_address = 6;</code>
       */
      public Builder setGlobcoverAddressBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000020;
        globcoverAddress_ = value;
        onChanged();
        return this;
      }

      // optional bool get_xapi = 7;
      private boolean getXapi_ ;
      /**
       * <code>optional bool get_xapi = 7;</code>
       */
      public boolean hasGetXapi() {
        return ((bitField0_ & 0x00000040) == 0x00000040);
      }
      /**
       * <code>optional bool get_xapi = 7;</code>
       */
      public boolean getGetXapi() {
        return getXapi_;
      }
      /**
       * <code>optional bool get_xapi = 7;</code>
       */
      public Builder setGetXapi(boolean value) {
        bitField0_ |= 0x00000040;
        getXapi_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional bool get_xapi = 7;</code>
       */
      public Builder clearGetXapi() {
        bitField0_ = (bitField0_ & ~0x00000040);
        getXapi_ = false;
        onChanged();
        return this;
      }

      // optional string reset_password_address = 8;
      private java.lang.Object resetPasswordAddress_ = "";
      /**
       * <code>optional string reset_password_address = 8;</code>
       */
      public boolean hasResetPasswordAddress() {
        return ((bitField0_ & 0x00000080) == 0x00000080);
      }
      /**
       * <code>optional string reset_password_address = 8;</code>
       */
      public java.lang.String getResetPasswordAddress() {
        java.lang.Object ref = resetPasswordAddress_;
        if (!(ref instanceof java.lang.String)) {
          java.lang.String s = ((com.google.protobuf.ByteString) ref)
              .toStringUtf8();
          resetPasswordAddress_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>optional string reset_password_address = 8;</code>
       */
      public com.google.protobuf.ByteString
          getResetPasswordAddressBytes() {
        java.lang.Object ref = resetPasswordAddress_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          resetPasswordAddress_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string reset_password_address = 8;</code>
       */
      public Builder setResetPasswordAddress(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000080;
        resetPasswordAddress_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string reset_password_address = 8;</code>
       */
      public Builder clearResetPasswordAddress() {
        bitField0_ = (bitField0_ & ~0x00000080);
        resetPasswordAddress_ = getDefaultInstance().getResetPasswordAddress();
        onChanged();
        return this;
      }
      /**
       * <code>optional string reset_password_address = 8;</code>
       */
      public Builder setResetPasswordAddressBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000080;
        resetPasswordAddress_ = value;
        onChanged();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:ServerInfo)
    }

    static {
      defaultInstance = new ServerInfo(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:ServerInfo)
  }

  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_ServerInfo_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_ServerInfo_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\036PATH/ServerInfoContainer.proto\"\314\001\n\nSer" +
      "verInfo\022\024\n\014rail_address\030\001 \001(\t\022\025\n\rriver_a" +
      "ddress\030\002 \001(\t\022\024\n\014lake_address\030\003 \001(\t\022\031\n\021co" +
      "astline_address\030\004 \001(\t\022\023\n\013poi_address\030\005 \001" +
      "(\t\022\031\n\021globcover_address\030\006 \001(\t\022\020\n\010get_xap" +
      "i\030\007 \001(\010\022\036\n\026reset_password_address\030\010 \001(\tB" +
      "\030\n\026com.chunkmapper.protoc"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
      new com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner() {
        public com.google.protobuf.ExtensionRegistry assignDescriptors(
            com.google.protobuf.Descriptors.FileDescriptor root) {
          descriptor = root;
          internal_static_ServerInfo_descriptor =
            getDescriptor().getMessageTypes().get(0);
          internal_static_ServerInfo_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_ServerInfo_descriptor,
              new java.lang.String[] { "RailAddress", "RiverAddress", "LakeAddress", "CoastlineAddress", "PoiAddress", "GlobcoverAddress", "GetXapi", "ResetPasswordAddress", });
          return null;
        }
      };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
  }

  // @@protoc_insertion_point(outer_class_scope)
}
